// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECYowg2r0d39AaL6z4j3YVwU7Q3PYOJg',
    appId: '1:1075529599362:web:d4e8aa63e083a9ffebe79b',
    messagingSenderId: '1075529599362',
    projectId: 'lung-cdss',
    authDomain: 'lung-cdss.firebaseapp.com',
    storageBucket: 'lung-cdss.firebasestorage.app',
    measurementId: 'G-TM7E7DTV7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAwYjsoBLybdDzTIoqkzOZbzKVa_2ASGE',
    appId: '1:1075529599362:android:87d974b0b880c531ebe79b',
    messagingSenderId: '1075529599362',
    projectId: 'lung-cdss',
    storageBucket: 'lung-cdss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxaIDga4oSqugEkqv1kVcJSrMTOQ3e5U',
    appId: '1:1075529599362:ios:46b362cac8aff90bebe79b',
    messagingSenderId: '1075529599362',
    projectId: 'lung-cdss',
    storageBucket: 'lung-cdss.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxaIDga4oSqugEkqv1kVcJSrMTOQ3e5U',
    appId: '1:1075529599362:ios:46b362cac8aff90bebe79b',
    messagingSenderId: '1075529599362',
    projectId: 'lung-cdss',
    storageBucket: 'lung-cdss.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDECYowg2r0d39AaL6z4j3YVwU7Q3PYOJg',
    appId: '1:1075529599362:web:6758cc0e623c1db8ebe79b',
    messagingSenderId: '1075529599362',
    projectId: 'lung-cdss',
    authDomain: 'lung-cdss.firebaseapp.com',
    storageBucket: 'lung-cdss.firebasestorage.app',
    measurementId: 'G-0SG60H140E',
  );
}
